development:
  :site_title: 'vhost-API UI'
  :api_url: 'http://localhost:9393'
  :api_ver: 1
  :session_key: 'rack.session'
  :threshholds:
    :display:
      :mailquota_warn: 65
      :mailquota_crit: 90
  :webmail_link: 'http://webmail.localhost.localdomain'

test:
  :site_title: 'vhost-API UI'
  :api_url: 'http://localhost:9393'
  :api_ver: 1
  :session_key: 'rack.session'
  :threshholds:
    :display:
      :mailquota_warn: 65
      :mailquota_crit: 90
  :webmail_link: 'http://webmail.localhost.localdomain'

production:
  :site_title: 'vhost-API UI'
  :api_url: 'https://api.example.com'
  :api_ver: 1
  :session_key: 'rack.session'
  :threshholds:
    :display:
      :mailquota_warn: 65
      :mailquota_crit: 90
  :webmail_link: 'https://webmail.example.com'
